[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Functions for API routes
[functions]
  directory = ".netlify/functions"

# Environment variables for Steam API (optional)
# Add these in Netlify dashboard if you get a Steam API key
# STEAM_WEB_API_KEY = "your_steam_api_key_here"

