[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Ensure proper handling of assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

